id = "moonlight"
name = "Moonlight"
version = "0.0.1"
schema_version = 1
authors = ["Rick-VA <rick@rickva.dev>"]
description = "Moonlight theme for Zed"
repository = "https://github.com/Rick-VA/Moonlight"